# stage1 as builder
FROM node:16-alpine as builder

# copy the package.json to install dependencies
COPY package.json package-lock.json ./

# Install the dependencies and make the folder
RUN npm install && mkdir /usr/app && mv ./node_modules ./usr/app

WORKDIR /usr/app

COPY . .

# Build the project and copy the files
RUN npm run build


FROM nginx:alpine

#!/bin/sh

CMD ["npm","run","start"]
EXPOSE 3000
# ENTRYPOINT ["nginx", "-g", "daemon off;"]
